server:
  port: 8010


spring:
  redis:
    host: 101.200.129.252
    port: 6379
    password:
    database: 0
    timeout: 3000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.129.252:3306/line_aagw?useunicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000
#设置文件输出位置
logging:
  pattern:
    #输出文件的格式
    file: "%d{yyyy-MM-dd HH:mm:ss} === [%thread] === %-5level === %logger{50} ==== %msg%n"
    #输出到控制台的格式
    console: " %d{yyyy-MM-dd HH:mm:ss} ---[%thread] --- %-5level ---%logger{50}--- %msg%n"
  level:
    root: info
  config: classpath:logback-spring.xml
